# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cockatrice/protobuf/management.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cockatrice.protobuf import common_pb2 as cockatrice_dot_protobuf_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cockatrice/protobuf/management.proto',
  package='protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n$cockatrice/protobuf/management.proto\x12\x08protobuf\x1a cockatrice/protobuf/common.proto\"6\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x0c\n\x04sync\x18\x03 \x01(\x08\"/\n\x0bPutResponse\x12 \n\x06status\x18\x01 \x01(\x0b\x32\x10.protobuf.Status\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\">\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\x0c\x12 \n\x06status\x18\x02 \x01(\x0b\x32\x10.protobuf.Status\"*\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04sync\x18\x02 \x01(\x08\"A\n\x0e\x44\x65leteResponse\x12\r\n\x05value\x18\x01 \x01(\x0c\x12 \n\x06status\x18\x02 \x01(\x0b\x32\x10.protobuf.Status\"\x1c\n\x0c\x43learRequest\x12\x0c\n\x04sync\x18\x01 \x01(\x08\"1\n\rClearResponse\x12 \n\x06status\x18\x01 \x01(\x0b\x32\x10.protobuf.Status2\xf3\x01\n\nManagement\x12\x34\n\x03Put\x12\x14.protobuf.PutRequest\x1a\x15.protobuf.PutResponse\"\x00\x12\x34\n\x03Get\x12\x14.protobuf.GetRequest\x1a\x15.protobuf.GetResponse\"\x00\x12=\n\x06\x44\x65lete\x12\x17.protobuf.DeleteRequest\x1a\x18.protobuf.DeleteResponse\"\x00\x12:\n\x05\x43lear\x12\x16.protobuf.ClearRequest\x1a\x17.protobuf.ClearResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[cockatrice_dot_protobuf_dot_common__pb2.DESCRIPTOR,])




_PUTREQUEST = _descriptor.Descriptor(
  name='PutRequest',
  full_name='protobuf.PutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='protobuf.PutRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='protobuf.PutRequest.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sync', full_name='protobuf.PutRequest.sync', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=138,
)


_PUTRESPONSE = _descriptor.Descriptor(
  name='PutResponse',
  full_name='protobuf.PutResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='protobuf.PutResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=187,
)


_GETREQUEST = _descriptor.Descriptor(
  name='GetRequest',
  full_name='protobuf.GetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='protobuf.GetRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=214,
)


_GETRESPONSE = _descriptor.Descriptor(
  name='GetResponse',
  full_name='protobuf.GetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='protobuf.GetResponse.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='protobuf.GetResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=278,
)


_DELETEREQUEST = _descriptor.Descriptor(
  name='DeleteRequest',
  full_name='protobuf.DeleteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='protobuf.DeleteRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sync', full_name='protobuf.DeleteRequest.sync', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=322,
)


_DELETERESPONSE = _descriptor.Descriptor(
  name='DeleteResponse',
  full_name='protobuf.DeleteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='protobuf.DeleteResponse.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='protobuf.DeleteResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=389,
)


_CLEARREQUEST = _descriptor.Descriptor(
  name='ClearRequest',
  full_name='protobuf.ClearRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sync', full_name='protobuf.ClearRequest.sync', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=419,
)


_CLEARRESPONSE = _descriptor.Descriptor(
  name='ClearResponse',
  full_name='protobuf.ClearResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='protobuf.ClearResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=421,
  serialized_end=470,
)

_PUTRESPONSE.fields_by_name['status'].message_type = cockatrice_dot_protobuf_dot_common__pb2._STATUS
_GETRESPONSE.fields_by_name['status'].message_type = cockatrice_dot_protobuf_dot_common__pb2._STATUS
_DELETERESPONSE.fields_by_name['status'].message_type = cockatrice_dot_protobuf_dot_common__pb2._STATUS
_CLEARRESPONSE.fields_by_name['status'].message_type = cockatrice_dot_protobuf_dot_common__pb2._STATUS
DESCRIPTOR.message_types_by_name['PutRequest'] = _PUTREQUEST
DESCRIPTOR.message_types_by_name['PutResponse'] = _PUTRESPONSE
DESCRIPTOR.message_types_by_name['GetRequest'] = _GETREQUEST
DESCRIPTOR.message_types_by_name['GetResponse'] = _GETRESPONSE
DESCRIPTOR.message_types_by_name['DeleteRequest'] = _DELETEREQUEST
DESCRIPTOR.message_types_by_name['DeleteResponse'] = _DELETERESPONSE
DESCRIPTOR.message_types_by_name['ClearRequest'] = _CLEARREQUEST
DESCRIPTOR.message_types_by_name['ClearResponse'] = _CLEARRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PutRequest = _reflection.GeneratedProtocolMessageType('PutRequest', (_message.Message,), dict(
  DESCRIPTOR = _PUTREQUEST,
  __module__ = 'cockatrice.protobuf.management_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.PutRequest)
  ))
_sym_db.RegisterMessage(PutRequest)

PutResponse = _reflection.GeneratedProtocolMessageType('PutResponse', (_message.Message,), dict(
  DESCRIPTOR = _PUTRESPONSE,
  __module__ = 'cockatrice.protobuf.management_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.PutResponse)
  ))
_sym_db.RegisterMessage(PutResponse)

GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETREQUEST,
  __module__ = 'cockatrice.protobuf.management_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.GetRequest)
  ))
_sym_db.RegisterMessage(GetRequest)

GetResponse = _reflection.GeneratedProtocolMessageType('GetResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETRESPONSE,
  __module__ = 'cockatrice.protobuf.management_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.GetResponse)
  ))
_sym_db.RegisterMessage(GetResponse)

DeleteRequest = _reflection.GeneratedProtocolMessageType('DeleteRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETEREQUEST,
  __module__ = 'cockatrice.protobuf.management_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.DeleteRequest)
  ))
_sym_db.RegisterMessage(DeleteRequest)

DeleteResponse = _reflection.GeneratedProtocolMessageType('DeleteResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELETERESPONSE,
  __module__ = 'cockatrice.protobuf.management_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.DeleteResponse)
  ))
_sym_db.RegisterMessage(DeleteResponse)

ClearRequest = _reflection.GeneratedProtocolMessageType('ClearRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLEARREQUEST,
  __module__ = 'cockatrice.protobuf.management_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.ClearRequest)
  ))
_sym_db.RegisterMessage(ClearRequest)

ClearResponse = _reflection.GeneratedProtocolMessageType('ClearResponse', (_message.Message,), dict(
  DESCRIPTOR = _CLEARRESPONSE,
  __module__ = 'cockatrice.protobuf.management_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.ClearResponse)
  ))
_sym_db.RegisterMessage(ClearResponse)



_MANAGEMENT = _descriptor.ServiceDescriptor(
  name='Management',
  full_name='protobuf.Management',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=473,
  serialized_end=716,
  methods=[
  _descriptor.MethodDescriptor(
    name='Put',
    full_name='protobuf.Management.Put',
    index=0,
    containing_service=None,
    input_type=_PUTREQUEST,
    output_type=_PUTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='protobuf.Management.Get',
    index=1,
    containing_service=None,
    input_type=_GETREQUEST,
    output_type=_GETRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='protobuf.Management.Delete',
    index=2,
    containing_service=None,
    input_type=_DELETEREQUEST,
    output_type=_DELETERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Clear',
    full_name='protobuf.Management.Clear',
    index=3,
    containing_service=None,
    input_type=_CLEARREQUEST,
    output_type=_CLEARRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MANAGEMENT)

DESCRIPTOR.services_by_name['Management'] = _MANAGEMENT

# @@protoc_insertion_point(module_scope)
