# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from cockatrice.protobuf import management_pb2 as cockatrice_dot_protobuf_dot_management__pb2


class ManagementStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Put = channel.unary_unary(
        '/protobuf.Management/Put',
        request_serializer=cockatrice_dot_protobuf_dot_management__pb2.PutRequest.SerializeToString,
        response_deserializer=cockatrice_dot_protobuf_dot_management__pb2.PutResponse.FromString,
        )
    self.Get = channel.unary_unary(
        '/protobuf.Management/Get',
        request_serializer=cockatrice_dot_protobuf_dot_management__pb2.GetRequest.SerializeToString,
        response_deserializer=cockatrice_dot_protobuf_dot_management__pb2.GetResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/protobuf.Management/Delete',
        request_serializer=cockatrice_dot_protobuf_dot_management__pb2.DeleteRequest.SerializeToString,
        response_deserializer=cockatrice_dot_protobuf_dot_management__pb2.DeleteResponse.FromString,
        )
    self.Clear = channel.unary_unary(
        '/protobuf.Management/Clear',
        request_serializer=cockatrice_dot_protobuf_dot_management__pb2.ClearRequest.SerializeToString,
        response_deserializer=cockatrice_dot_protobuf_dot_management__pb2.ClearResponse.FromString,
        )


class ManagementServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Put(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Clear(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ManagementServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Put': grpc.unary_unary_rpc_method_handler(
          servicer.Put,
          request_deserializer=cockatrice_dot_protobuf_dot_management__pb2.PutRequest.FromString,
          response_serializer=cockatrice_dot_protobuf_dot_management__pb2.PutResponse.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=cockatrice_dot_protobuf_dot_management__pb2.GetRequest.FromString,
          response_serializer=cockatrice_dot_protobuf_dot_management__pb2.GetResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=cockatrice_dot_protobuf_dot_management__pb2.DeleteRequest.FromString,
          response_serializer=cockatrice_dot_protobuf_dot_management__pb2.DeleteResponse.SerializeToString,
      ),
      'Clear': grpc.unary_unary_rpc_method_handler(
          servicer.Clear,
          request_deserializer=cockatrice_dot_protobuf_dot_management__pb2.ClearRequest.FromString,
          response_serializer=cockatrice_dot_protobuf_dot_management__pb2.ClearResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protobuf.Management', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
